### ISSUE TITLE
branch:merging..... ,results.plot views

### ISSUE THREAD

**Issue by xhajnal** [sybila/pithya-gui#18]
Flow:
`NormalFlow -> Results.addplot.click -> Results.addplot.click -> Results.plot(2).horizontal.set(x) -> Results.VF.plot(2).scaleIn(0.8) |  Results.VF.plot(2).scaleIn(0.6)`

Results in cycle of changes 
![image](https://cloud.githubusercontent.com/assets/23458520/20978955/28ed7fba-bcab-11e6-9edf-5555f070608e.png)
![image](https://cloud.githubusercontent.com/assets/23458520/20978990/434e65d6-bcab-11e6-9cd4-7de5a8d0e601.png)

**Comment by martindemko** [comment]
I know about it, it can happen with every slider, for now I don't know how to fix it

**Comment by martindemko** [comment]
solved
