### ISSUE TITLE
Results, Selecting same parameter for axes deg_x,deg_x

### ISSUE THREAD

**Issue by xhajnal** [sybila/pithya-gui#22]
`Results.plot(1).setHorizontal(deg_x) ->Results.plot(1).setVertical(deg_x)`

The shown plot for parameter space (or parameter dependence) is only 1-dimensional. (Fig. 1)
![image](https://cloud.githubusercontent.com/assets/23458520/21011120/128ade02-bd50-11e6-9903-5d0f735dbeab.png)

**Problem:**
The result is not intuitive

**Solve:**
- Anable choosing vertical axis as "None" for such 1-dimensional plot
or 
- explicitly warn user that the plot is 1-dimensional
or 
- really show 2-dimensional plot for deg_x vs. deg_x

**Comment by martindemko** [comment]
This will be explained in the manual. Showing 2D plot of same parameters/variables doesn't make sense

**Comment by xhajnal** [comment]
imho manual is must have, but the tool itself should be changed in order to make this thing intuitive.

**Comment by daemontus** [comment]
I would propose this solution:
As soon as rest of the tool is stabilized, a small Javascript function will be added which will disable the option with the same name in the second dropdown box right after the first one is fixed.

So, if I select deg_x in the first dropdown, the javascript function will automatically remove/disable it in the second dropdown. This way the user can't select it. I will try to do it as soon as there is a bit more time, so please keep this open :)

**Comment by martindemko** [comment]
But it is not an issue, it is like that on purpose

**Comment by daemontus** [comment]
Ok, but then I would use the suggested "None" option. Because selecting the same variable two times to get a one dimensional plot really doesn't make much sense :)

**Comment by daemontus** [comment]
Fixed in clean-up:
Solution: The variable/parameter selectors don't allow to select one dimensional plot unless necessary (one dim. models). In such cases, a dummy "(none)" variable is added (it's axis are not shown) which serves as a visual aid as for what is happening
