### ISSUE TITLE
Experiment number

### ISSUE THREAD

**Issue by xhajnal** [sybila/pithya-gui#34]
When generating approximation or other feature creating new experiment, the current experiment doesn't change. I think it would be more user-friendly if shown experiment would jump into the newest.

**Comment by martindemko** [comment]
For me it is other way round because user can be doing something and it would be unpleasant if experiment changes unexpectedly (which could happen specially right after parameter synthesis is done). But it is opened for discussion.

**Comment by martindemko** [comment]
since experiments are not currently in consideration this issue is no more needed
