### ISSUE TITLE
Explorer, number of parameters

### ISSUE THREAD

**Issue by xhajnal** [sybila/pithya-gui#35]
After some changes in parameters in the model I managed to get this error, showing nuber of parameter in Explorer didn't change according to the model.
![screenshot 2016-12-19 02 05 11](https://cloud.githubusercontent.com/assets/23458520/21359137/7f17ad9a-c6db-11e6-8b97-232f1577ef2a.png)

**Comment by xhajnal** [comment]
I will try to reproduce this issue.

**Comment by martindemko** [comment]
not possible any more
