### ISSUE TITLE
Explorer, not deleting plots

### ISSUE THREAD

**Issue by xhajnal** [sybila/pithya-gui#9]
Explorer.plot.cancel / Explorer.Vector field.plot
result:  Explorer.plot.cancel does not delete plot, problem with cash, plot saving or smth
After adding deleted plot, programme shows some plot with trajectory in Vector field (not default plot without trajectory)

======================================================
LEGEND:
ModulesDict:= {Model editor:Editor,Model explorer:Explorer,Result explorer:Result}

**Comment by martindemko** [comment]
so far not replicable
